function [fitresult, gof] = createFits(XI, YI, imgX_cut)
%CREATEFITS(XI,YI,IMGX_CUT)
%  Create fits.
%
%  Data for 'untitled fit 2' fit:
%      X Input : XI
%      Y Input : YI
%      Z Output: imgX_cut
%  Data for 'untitled fit 1' fit:
%      X Input : XI
%      Y Input : YI
%      Z Output: imgX_cut
%  Data for 'untitled fit 3' fit:
%      X Input : XI
%      Y Input : YI
%      Z Output: imgX_cut
%  Data for 'untitled fit 4' fit:
%      X Input : XI
%      Y Input : YI
%      Z Output: imgX_cut
%  Data for 'untitled fit 5' fit:
%      X Input : XI
%      Y Input : YI
%      Z Output: imgX_cut
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Dec-2015 10:12:12

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 5, 1 );
gof = struct( 'sse', cell( 5, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 2'.
[xData, yData, zData] = prepareSurfaceData( XI, YI, imgX_cut );

% Set up fittype and options.
ft = fittype( '124*exp(-((x - 3.1)^2/b + (y - 15.1)^2/c))', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.408719846112552 0.594896074008614];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult{1}, [xData, yData], zData );
legend( h, 'untitled fit 2', 'imgX_cut vs. XI, YI', 'Location', 'NorthEast' );
% Label axes
xlabel( 'XI' );
ylabel( 'YI' );
zlabel( 'imgX_cut' );
grid on

%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( XI, YI, imgX_cut );

% Set up fittype and options.
ft = fittype( '35*exp(-((x - 5)^2/b + (y - 27)^2/c))', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.262482234698333 0.801014622769739];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult{2}, [xData, yData], zData );
legend( h, 'untitled fit 1', 'imgX_cut vs. XI, YI', 'Location', 'NorthEast' );
% Label axes
xlabel( 'XI' );
ylabel( 'YI' );
zlabel( 'imgX_cut' );
grid on

%% Fit: 'untitled fit 3'.
[xData, yData, zData] = prepareSurfaceData( XI, YI, imgX_cut );

% Set up fittype and options.
ft = fittype( '171*exp(-((x - 11)^2/b + (y - 23)^2/c))', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.335356839962797 0.679727951377338];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult{3}, gof(3)] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 3' );
h = plot( fitresult{3}, [xData, yData], zData );
legend( h, 'untitled fit 3', 'imgX_cut vs. XI, YI', 'Location', 'NorthEast' );
% Label axes
xlabel( 'XI' );
ylabel( 'YI' );
zlabel( 'imgX_cut' );
grid on

%% Fit: 'untitled fit 4'.
[xData, yData, zData] = prepareSurfaceData( XI, YI, imgX_cut );

% Set up fittype and options.
ft = fittype( '55*exp(-((x - 11)^2/b + (y - 40)^2/c))', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.744074260367462 0.500022435590201];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult{4}, gof(4)] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 4' );
h = plot( fitresult{4}, [xData, yData], zData );
legend( h, 'untitled fit 4', 'imgX_cut vs. XI, YI', 'Location', 'NorthEast' );
% Label axes
xlabel( 'XI' );
ylabel( 'YI' );
zlabel( 'imgX_cut' );
grid on

%% Fit: 'untitled fit 5'.
[xData, yData, zData] = prepareSurfaceData( XI, YI, imgX_cut );

% Set up fittype and options.
ft = fittype( '255*exp(-((x - 18.8)^2/b + (y - 24.8)^2/c))', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.818148553859625 0.817547092079286];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult{5}, gof(5)] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 5' );
h = plot( fitresult{5}, [xData, yData], zData );
legend( h, 'untitled fit 5', 'imgX_cut vs. XI, YI', 'Location', 'NorthEast' );
% Label axes
xlabel( 'XI' );
ylabel( 'YI' );
zlabel( 'imgX_cut' );
grid on


